# Generated by Django 5.1.1 on 2024-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name_db_column', max_length=100, verbose_name='First Name')),
                ('education', models.CharField(choices=[('PHD', 'doctora'), ('MST', 'arshad')], max_length=100, verbose_name='Education')),
            ],
        ),
    ]
